// Copies the canonical OpenAPI spec and branding assets into ndk_frontend/ so the
// Scalar frontend has everything it needs as a self-contained static bundle.
// Single source of truth: src/spec/openapi.yaml — ndk_frontend/openapi.yaml is a build artifact.
import { copyFileSync, mkdirSync, existsSync, readdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const frontend = resolve(root, "ndk_frontend");
mkdirSync(frontend, { recursive: true });

const assets = [
  ["src/spec/openapi.yaml", "ndk_frontend/openapi.yaml"],
  // Branding lives under src/ so ndk_frontend/ stays buildable even if portal/ is
  // wiped and regenerated by APIMatic.
  ["src/static/images/nust-logo.png", "ndk_frontend/nust-logo.png"],
  ["src/static/images/favicon.png", "ndk_frontend/favicon.png"],
];

let copied = 0;
for (const [from, to] of assets) {
  const src = resolve(root, from);
  if (!existsSync(src)) {
    console.warn(`! skipped (missing): ${from}`);
    continue;
  }
  copyFileSync(src, resolve(root, to));
  console.log(`✓ ${from} → ${to}`);
  copied++;
}
console.log(`\nSynced ${copied}/${assets.length} asset(s) into ndk_frontend/.`);

// Copy the generated SDK zips so the frontend can offer per-language downloads.
const sdkSrc = resolve(root, "portal/static/sdks");
if (existsSync(sdkSrc)) {
  const sdkDest = resolve(frontend, "sdks");
  mkdirSync(sdkDest, { recursive: true });
  let zips = 0;
  for (const file of readdirSync(sdkSrc)) {
    if (file.endsWith(".zip")) {
      copyFileSync(resolve(sdkSrc, file), resolve(sdkDest, file));
      zips++;
    }
  }
  console.log(`Copied ${zips} SDK zip(s) into ndk_frontend/sdks/.`);
} else {
  console.warn("! SDK zips not found (portal/static/sdks) — downloads will be missing.");
}
